### ISSUE TITLE
升级 frps v0.52.1 后，界面参数显示异常

### ISSUE THREAD

**Issue by jikunchong** [yhl452493373/frps-panel#11]
frps v0.52.x 版本配置文件变更为 toml，我按如下方式配置：
```TOML
[[httpPlugins]]
name = "multiuser-manager"
addr = "https://127.0.0.1:7200"
path = "/handler"
ops = ["Login", "NewWorkConn", "NewUserConn", "NewProxy", "Ping"]
```

结果 frps 的控制台显示正常，但 frps-panel 这边，除了 frps 的版本号，其它的配置信息显示不出来，下面的各类型代理列表也均出现转圈：
![frps-0 52 1](https://github.com/yhl452493373/frps-panel/assets/15645751/c30a0518-4abc-4835-bb33-da29bfcf66ba)
