### ISSUE TITLE
7500 port got connection refused

### ISSUE THREAD

**Issue by Xbeninni** [yhl452493373/frps-panel#16]
Get "http://127.0.0.1:7500/api/serverinfo": dial tcp 127.0.0.1:7500: connect: connection refused
![7500err](https://github.com/yhl452493373/frps-panel/assets/33538292/819168f4-eb4d-4a07-8d1c-abce6749041a)

**Comment by OnieMa** [comment]
frps 配置文件没有开启web界面访问

**Comment by yhl452493373** [comment]
把frps的web访问权限开启。
---
frp 0.52.0以下，使用1.x版本插件，`frps.ini`增加如下内容：
```ini
[common]
dashboard_addr = 0.0.0.0
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
```
frp 0.52.0即以上，使用2.x版本插件，`frps.toml`增加如下内容
```toml
#以下内容需和bindPort属性同级
webServer.addr = "127.0.0.1"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"
```
或
```toml
[webServer]
addr = "127.0.0.1"
port = 7500
user = "admin"
password = "admin"
```
