### ISSUE TITLE
从配置文件中读取配置时，配置项增加默认值

### ISSUE THREAD

**Issue by jikunchong** [yhl452493373/frps-panel#2]
现象：
1. 第一个用户 abc 配置的端口和子域都能正常访问，而其它用户的不行。 
2. Frp 面板中，用户列表界面一直转圈，不能加载用户列表信息。

版本：1.7.1
`frps-tokens.toml` 配置如下：

```toml
# frps-tokens.toml
[tokens]
   [tokens.abc]
      user = "abc"
      token = "805e2bax-xxx"
      comment = "abc with token 805e2bax"
      ports = ["11000-11999", "16000-18999", "19000-19999"]
      subdomains = ["www", "asset", "code", "vault", "tools"]
      enable = true
   [tokens.def.ghi]
      user = "def.ghi"
      token = "88ecfd0x-yyy"
      comment = "def.ghi with token 88ecfd0x"
      # n5095: 21000-21999
      ports = ["21000-21999"]
      subdomains = ["n5095-unraid", "n5095-ds3622xs", "n5095-frpc"]
      enable = true
   [tokens.tao.wan]
      user = "tao.wan"
      token = "87caa9dx-zzz"
      comment = "tao.wan with token 87caa9dx"
      # x99: 22000-22999
      ports = ["22000-22999"]
      subdomains = ["x99-frpc"]
      enable = true
```
