### ISSUE TITLE
增加 subdomain 前缀通配符和配额数量限制

### ISSUE THREAD

**Issue by jikunchong** [yhl452493373/frps-panel#3]
分配给某个用户固定的前缀子域名（比如，以“try-”开头），避免每次都要去单个维护。
比如：
```toml
#frps-tokens.toml
[tokens]
   [tokens.user1]
      user = "user1"
      token = "token1"
      comment = "user1 with token1"
      ports = [8080, "10000-10200"]
      domains = [""]
      subdomains = ["web01", "try-*"]
      enable = true
```
