### ISSUE TITLE
frps dashboard TLS mode 启用时，frps-panel.toml 中如何兼容配置 https 连接?

### ISSUE THREAD

**Issue by jikunchong** [yhl452493373/frps-panel#4]
```ini
# frps.ini (frps v0.51.3)

# dashboard TLS mode
dashboard_tls_mode = true
dashboard_tls_cert_file = /cert/server.crt
dashboard_tls_key_file = /cert/server.key
```

此时，frps-panel.toml 中应该如何配置，才能通过 https 来连接？

```toml
# frp dashboard info ?
dashboard_addr = "127.0.0.1"
dashboard_port = 7500
dashboard_user = "admin"
dashboard_pwd = "admin"
```
